### ISSUE TITLE
realtime_web npm error in docker

### ISSUE THREAD

**Issue by jfoucher** [supabase/realtime#45] opened 2020-05-29 21:48 UTC
This is what I get when trying to run this project according to the readme:
```
web_1       | npm ERR! path /usr/src/service/node_modules/npm/node_modules/cliui/node_modules/ansi-regex/package.json.1314949609
web_1       | npm ERR! code ENOENT
web_1       | npm ERR! errno -2
web_1       | npm ERR! syscall open
web_1       | npm ERR! enoent ENOENT: no such file or directory, open '/usr/src/service/node_modules/npm/node_modules/cliui/node_modules/ansi-regex/package.json.1314949609'
web_1       | npm ERR! enoent This is related to npm not being able to find a file.
web_1       | npm ERR! enoent
web_1       |
web_1       | npm ERR! A complete log of this run can be found in:
web_1       | npm ERR!     /root/.npm/_logs/2020-05-29T21_44_32_747Z-debug.log
realtime_web_1 exited with code 254
```
The db and realtime images work fine.
Any advice ?
Thanks

**Comment by kiwicopple** [comment] 2020-05-31 01:52
I just tested using a fresh instance and I wasn't able to reproduce this. It shouldn't be anything to do with your environment since it's docker. Can you try to rebuild?

```
docker-compose down --remove-orphans 
docker-compose build
docker-compose up --force-recreate --build
```

Let me know if that works.

**Comment by jfoucher** [comment] 2020-05-31 10:56
Nope, same thing sorry :

```
web_1       | npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
web_1       | npm WARN deprecated mkdirp@0.5.3: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
web_1       | npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
web_1       | npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
web_1       | npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
web_1       | npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/chokidar/node_modules/fsevents):
web_1       | npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
web_1       | npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules/fork-ts-checker-webpack-plugin/node_modules/chokidar/node_modules/fsevents):
web_1       | npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
web_1       | npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules/webpack/node_modules/chokidar/node_modules/fsevents):
web_1       | npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
web_1       | npm WARN sass-loader@8.0.2 requires a peer of node-sass@^4.0.0 but none is installed. You must install peer dependencies yourself.
web_1       | npm WARN sass-loader@8.0.2 requires a peer of sass@^1.3.0 but none is installed. You must install peer dependencies yourself.
web_1       | npm WARN sass-loader@8.0.2 requires a peer of fibers@>= 3.1.0 but none is installed. You must install peer dependencies yourself.
web_1       | npm WARN supabase-realtime-example@1.0.0 No repository field.
web_1       |
web_1       | npm ERR! path /usr/src/service/node_modules/npm/node_modules/yargs/node_modules/y18n/package.json.851568467
web_1       | npm ERR! code ENOENT
web_1       | npm ERR! errno -2
web_1       | npm ERR! syscall open
web_1       | npm ERR! enoent ENOENT: no such file or directory, open '/usr/src/service/node_modules/npm/node_modules/yargs/node_modules/y18n/package.json.851568467'
web_1       | npm ERR! enoent This is related to npm not being able to find a file.
web_1       | npm ERR! enoent
web_1       |
web_1       | npm ERR! A complete log of this run can be found in:
web_1       | npm ERR!     /root/.npm/_logs/2020-05-31T10_54_38_127Z-debug.log
realtime_web_1 exited with code 254
```

**Comment by kiwicopple** [comment] 2020-05-31 12:06
strange. Do you have any more details about your environment? Or anything that could help to reproduce the error?

**Comment by jfoucher** [comment] 2020-05-31 15:28
Mac OS 10.15.4 (19E2269)
```
$ docker -v
Docker version 19.03.10, build 9424aea
```
```
$ docker-compose -v
docker-compose version 1.25.5, build unknown
```
```
$ docker-machine -v
docker-machine version 0.16.2, build bd45ab1
```
Anything else ?

**Comment by kiwicopple** [comment] 2020-06-12 11:01
Sorry for the incommunicado @jfoucher . 

I think it might be easier in this case to side-step docker for the frontend. Could you please follow the steps in this one? 
https://github.com/supabase/realtime/blob/master/examples/next-js/README.md

You can run them in 2 separate terminals - one for the backend and one for the frontend.

I also set up a simple NodeJS example here: https://github.com/supabase/realtime/blob/master/examples/node-js/README.md

**Comment by kiwicopple** [comment] 2020-06-18 11:13
I'll close this up for now, but feel free to reopen if you can't get the instructions above to work

**Closed by kiwicopple** 2020-06-18 11:13 UTC
