### ISSUE TITLE
Presence realtime not working locally

### ISSUE THREAD

**Issue by agubler** [supabase/realtime#353] opened 2022-11-23 10:10 UTC
# Bug report

## Describe the bug

I recently updated to the latest CLI that included support for the latest realtime functionality (https://github.com/supabase/cli/pull/594), however the presence capability is not working as expected locally with version `v1.0.0-rc.11`, the connection successfully connects and then errors meaning.

## To Reproduce

I have setup an reproduction here https://github.com/agubler/supabase-realtime-repro/tree/presence-issue with instructions on how to reproduce in the README.md.

## Expected behavior

Locally when two people join the "chat" then it should show and also when they "leave", this works when connected to supabase remotely.

## Screenshots / Error

```
** (UndefinedFunctionError) function RealtimeWeb.RealtimeChannel.handle_out/3 is undefined or private
    (realtime 2.0.0) RealtimeWeb.RealtimeChannel.handle_out("presence_diff", %{joins: %{"aa" => %{metas: [%{phx_ref: "Fyou3QmKfki7iAsB"}]}}, leaves: %{}}, %Phoenix.Socket{assigns: %{access_token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0", ack_broadcast: false, channel_name: "room-1", claims: %{"exp" => 1983812996, "iss" => "supabase-demo", "role" => "anon"}, confirm_token_ref: #Reference<0.2200908005.3418619905.231531>, is_new_api: true, jwt_secret: "iNjicxc4+llvc9wovDvqymwfnj9teWMlyOIbJ8Fh6j2WNU8CIJ2ZgjR6MUIKqSmeDmvpsKLsZ9jgXJmQPpwL8w==", limits: %{max_concurrent_users: 300, max_events_per_second: 100}, log_level: :error, pg_change_params: [], pg_sub_ref: nil, postgres_cdc_module: Extensions.PostgresCdcRls, postgres_extension: %{"db_host" => "e96tXstkn+jtFWJi0eBr+m3INdFm15wSEW0bMvP2ryY=", "db_name" => "sWBpZNdjggEPTQVlI52Zfw==", "db_password" => "sWBpZNdjggEPTQVlI52Zfw==", "db_port" => "MqmbZ5ZiXXFlSy8FeFYPAQ==", "db_user" => "sWBpZNdjggEPTQVlI52Zfw==", "ip_version" => 4, "poll_interval_ms" => 100, "poll_max_changes" => 100, "poll_max_record_bytes" => 1048576, "publication" => "supabase_realtime", "region" => "us-east-1", "slot_name" => "supabase_realtime_replication_slot"}, presence_key: "aa", rate_counter: %Realtime.RateCounter{id: {:limit, :tenant_events, "realtime"}, avg: 1.0, bucket: [1], max_bucket_len: 60, tick: 1000, tick_ref: #Reference<0.2200908005.3418619905.231516>, idle_shutdown: :infinity, idle_shutdown_ref: nil}, self_broadcast: false, tenant: "realtime", tenant_token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0", tenant_topic: "realtime:room-1"}, channel: RealtimeWeb.RealtimeChannel, channel_pid: #PID<0.2926.0>, endpoint: RealtimeWeb.Endpoint, handler: RealtimeWeb.UserSocket, id: "user_socket:realtime", joined: true, join_ref: "1", private: %{log_handle_in: :debug, log_join: :info}, pubsub_server: Realtime.PubSub, ref: nil, serializer: Phoenix.Socket.V1.JSONSerializer, topic: "realtime:room-1", transport: :websocket, transport_pid: #PID<0.2924.0>})
    (phoenix 1.6.13) lib/phoenix/channel/server.ex:327: Phoenix.Channel.Server.handle_info/2
    (stdlib 4.0.1) gen_server.erl:1120: :gen_server.try_dispatch/4
    (stdlib 4.0.1) gen_server.erl:1197: :gen_server.handle_msg/6
    (stdlib 4.0.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Last message: %Phoenix.Socket.Broadcast{topic: "realtime:room-1", event: "presence_diff", payload: %{joins: %{"aa" => %{metas: [%{phx_ref: "Fyou3QmKfki7iAsB"}]}}, leaves: %{}}}
State: %Phoenix.Socket{assigns: %{access_token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0", ack_broadcast: false, channel_name: "room-1", claims: %{"exp" => 1983812996, "iss" => "supabase-demo", "role" => "anon"}, confirm_token_ref: #Reference<0.2200908005.3418619905.231531>, is_new_api: true, jwt_secret: "iNjicxc4+llvc9wovDvqymwfnj9teWMlyOIbJ8Fh6j2WNU8CIJ2ZgjR6MUIKqSmeDmvpsKLsZ9jgXJmQPpwL8w==", limits: %{max_concurrent_users: 300, max_events_per_second: 100}, log_level: :error, pg_change_params: [], pg_sub_ref: nil, postgres_cdc_module: Extensions.PostgresCdcRls, postgres_extension: %{"db_host" => "e96tXstkn+jtFWJi0eBr+m3INdFm15wSEW0bMvP2ryY=", "db_name" => "sWBpZNdjggEPTQVlI52Zfw==", "db_password" => "sWBpZNdjggEPTQVlI52Zfw==", "db_port" => "MqmbZ5ZiXXFlSy8FeFYPAQ==", "db_user" => "sWBpZNdjggEPTQVlI52Zfw==", "ip_version" => 4, "poll_interval_ms" => 100, "poll_max_changes" => 100, "poll_max_record_bytes" => 1048576, "publication" => "supabase_realtime", "region" => "us-east-1", "slot_name" => "supabase_realtime_replication_slot"}, presence_key: "aa", rate_counter: %Realtime.RateCounter{id: {:limit, :tenant_events, "realtime"}, avg: 1.0, bucket: [1], max_bucket_len: 60, tick: 1000, tick_ref: #Reference<0.2200908005.3418619905.231516>, idle_shutdown: :infinity, idle_shutdown_ref: nil}, self_broadcast: false, tenant: "realtime", tenant_token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0", tenant_topic: "realtime:room-1"}, channel: RealtimeWeb.RealtimeChannel, channel_pid: #PID<0.2926.0>, endpoint: RealtimeWeb.Endpoint, handler: RealtimeWeb.UserSocket, id: "user_socket:realtime", joined: true, join_ref: "1", private: %{log_handle_in: :debug, log_join: :info}, pubsub_server: Realtime.PubSub, ref: nil, serializer: Phoenix.Socket.V1.JSONSerializer, topic: "realtime:room-1", transport: :websocket, transport_pid: #PID<0.2924.0>}
10:08:59.809 project=realtime external_id=realtime [error] GenServer #PID<0.2933.0> terminating
```

## System information

- OS: MacOs
- Browser: Chrome
- Version of supabase-js: 1.15.0
- Version of Node.js: 16.5.1

## Additional context

N/A

**Comment by w3b6x9** [comment] 2022-11-23 22:19
@agubler I'm going to investigate. In the meantime, you should upgrade your client to `supabase-js` v2. Presence only works with v2.

**Comment by w3b6x9** [comment] 2022-11-23 22:20
@agubler I think there might have been issues with `v1.0.0-rc.11`. Try the latest v1.0.0-rc.12.

**Comment by agubler** [comment] 2022-11-23 22:22
I would need the cli to be updated to use that version if possible?

Presence worked with the real supabase using that version of the  JavaScript sdk

**Comment by w3b6x9** [comment] 2022-11-23 22:24
> Presence worked with the real supabase using that version of the JavaScript sdk

@agubler can you share a code snippet of your client interacting with Realtime Presence?

**Comment by agubler** [comment] 2022-11-23 22:25
It's all in the GitHub repo

**Comment by agubler** [comment] 2022-11-23 22:55
@w3b6x9 oh my bad I put the cli version not the sdk, I am using v2. Ooops sorry

**Comment by w3b6x9** [comment] 2022-11-23 23:28
@agubler no worries! I saw the version after looking at your repo.

I was able to reproduce your issue via CLI but Presence is working fine when I point the client to a hosted Supabase project in production. The Realtime we run in CLI is the same we run in production so this is odd.

I'll have to keep investigating to find the root cause.

**Comment by w3b6x9** [comment] 2022-11-26 05:36
@agubler I put up a fix for this that we'll release soon. Here's the PR over in the CLI repo: https://github.com/supabase/cli/pull/640.

**Closed** 2022-11-26 16:25 UTC
Labels: bug

**Comment by agubler** [comment] 2022-11-28 10:24
@w3b6x9 Thanks for all the help, this seems to be working 😄
