### ISSUE TITLE
realtime only emitting `DELETE` events (no `INSERT` or `UPDATE`)

### ISSUE THREAD

**Issue by tconroy** [supabase/realtime#213] opened 2021-12-26 18:10 UTC
# Bug report
realtime only emitting `DELETE` events (no `INSERT` or `UPDATE`)

## Describe the bug
When I perform an `INSERT` or `UPDATE` to a table with realtime + RLS enabled, I do not receive any realtime event: 

```typescript
supabase
    .from('*')
    .on('*', (payload) => {
      console.log(`${payload.eventType} received: `, payload);
    })
    .subscribe();
```

`DELETE` events are correctly received.

The user has appropriate RLS permissions, because all data correctly loads on the client via supabase cllient `REST` calls. 

## To Reproduce
Unfortunately not able to share an example because it would be difficult to decouple the issue I'm seeing from domain-specific app code. However, here is my configuration:

**1. replication enabled:**
<img width="1408" alt="Screen Capture 2021-12-26 at 11 47 45@2x" src="https://user-images.githubusercontent.com/1609336/147414858-a97311d8-7e69-452d-a461-ad8b390b3421.png">

**2. replication enabled on tables:**
![Screen Capture 2021-12-26 at 11 48 29@2x](https://user-images.githubusercontent.com/1609336/147414908-ce5c8a82-bbca-47f6-8bcb-9f9c1ceb47a7.png)

**3. Subscription configuration:**
```typescript
supabase
    .from('*')
    .on('*', (payload) => {
      console.log(`${payload.eventType} received: `, payload);
    })
    .subscribe();
```

## Expected behavior
When I perform an `INSERT` or `UPDATE` on entities (such as `board_lists` table or `board_cards` table), I expect to see the following logged:

```
INSERT received: {payload data}
```

However, I **do not** see any realtime event **except** for `DELETE` operations, which are behaving as expected.

I am able to correctly perform `INSERT`, `UPDATE` and `READ` events on the client via the Supabase client/REST API, so I know that the RLS policies are not preventing the user from performing these operations.

## System / versions
* MacOS latest
* Node @ v17.2.0
* Yarn @ 1.22.17
* @supabase/supabase-js@1.29.0
* @supabase/realtime-js@^1.3.3
* @supabase/gotrue-js@^1.21.7
* @supabase/postgrest-js@^0.35.0

**Comment by tconroy** [comment] 2021-12-26 20:14
So it does seem to be something related to RLS policies. But I'm not sure exactly what the cause is.

My table `board_cards` has RLS Enabled with the following policy (`ALL`):
```
is_member_of_list(uid(), list_id)
```

This calls a [custom Postgres function](https://supabase.com/docs/guides/database/functions), `is_member_of_list()`:
<img width="642" alt="Screen Capture 2021-12-26 at 15 13 58@2x" src="https://user-images.githubusercontent.com/1609336/147419046-02f8d08b-e06c-4c6f-9b64-fc66ad1ba173.png">


which has this definition:

```

SELECT EXISTS (
  SELECT 1
  FROM team_memberships tm
  WHERE tm.user_id = uid
  AND tm.team_id = (
    SELECT team_id
    FROM team_boards tb
    WHERE tb.id = (
      SELECT board_id
      FROM board_lists bl
      WHERE bl.id = list_id
    )
  ) 
)
```

**This works correctly for supabase client/REST calls**. However, it seems to break realtime?

**Comment by GaryAustin1** [comment] 2021-12-27 01:24
Just throwing a random thought on this.  Realtime has some user faking to be authorized with a uid, etc.  What if the search path of that user does not cover auth.  I always use auth.uid() in my RLS.  You show using uid() without auth....

**Comment by tconroy** [comment] 2021-12-27 16:57
Hi @GaryAustin1 ,

> edit: I'm confused how your client would find uid() though as somewhere the search path has to include auth if you don't specify it with auth.uid().

I've noticed that, when adding my RLS policies via the Supabase dashboard, the `auth` part of `auth.uid()` is stripped out on save by Supabase. So I did some testing via a direct pg connection and noticed that calling `uid()` works just fine without the `auth` part. This seems to be how Supabase uses it as well when adding through the dashboard.

**Comment by olirice** [comment] 2021-12-27 19:14
The issue is related to the way PostgreSQL's `search_path` setting is manipulated to apply row level security policies in the security engine

There is a PR open + under review that resolves the issue and is expected to roll out within a few days.

​If this issue is blocking development on your project, you can avoid it until the fix is pushed by fully qualifying all references to tables/functions/views/etc within your RLS policies

e.g. `public.team_memberships` vs `team_memberships`

**Comment by tconroy** [comment] 2021-12-27 19:21
Hi @olirice - appreciate your email reply and response to this thread! 

I can confirm that your suggestion fixes the issue! 🎉  I updated my above RLS policy to use a function with the following definition (note the addition of the schema qualifier `public`):
```
SELECT EXISTS (
 SELECT 1
 FROM public.team_memberships tm
 WHERE tm.user_id = auth.uid()
 AND tm.team_id = (
   SELECT team_id
   FROM public.team_boards tb
   WHERE tb.id = (
     SELECT board_id
     FROM public.board_lists bl
     WHERE bl.id = list_id
   )
 )
)
```

Looking forward to that PR being merged as I have a lot of RLS I need to update! :-)

**Comment by w3b6x9** [comment] 2021-12-28 05:34
Related issue: https://github.com/supabase/supabase/issues/4683

**Comment by tconroy** [comment] 2021-12-28 21:18
Hi again @olirice, @w3b6x9 👋 

Playing with this some more today, and I'm now running into other issues with Realtime + RLS. Not sure if it's directly related to this issue, but it seems like if I try to target row-level changes, I do not receive updates.

ie this is working correctly:
```typescript
// ✅ this is working correctly (able to receive INSERT, UPDATE and DELETE events):
const subscription = await supabase
  .from('*')
  .on('*', handler)
  .subscribe();

// ❌ this is NOT working correctly (unable to receive INSERT, UPDATE and DELETE events):
const subscription = await supabase
  .from(`board_cards:list_id=eq.${someId}`)
  .on('*', handler)
  .subscribe();
```

In both scenarios, I am manipulating the exact same entities. The insert/update propagates to the catch-all `*` subscription, but not to the more specific row-level subscription.

And input much appreciated! :) I'm new to RLS so very possible I am simply doing something wrong.

**Comment by GaryAustin1** [comment] 2021-12-28 21:31
I had a RLS using a function and changed it up with path info and DO NOT have an issue using messages:room_key=eq.roomkey.  It is a text room key.  My non RLS realtime uses a userID row level qualifier and it also works.

**Comment by tconroy** [comment] 2021-12-28 22:06
Thank you for the help! Turns out I was setting the schema (ie `public.board_cards`) in the subscription. Removing that fixes it!

**Comment by jonlambert** [comment] 2022-01-01 20:16
Not sure whether this is related to my issue, but I'm unable to receive any change events at all from a hosted Supabase project.

```ts
const supabase = createClient(supabaseUrl, supabaseAnonKey);

supabase
      .from('*')
      .on('*', console.log)
      .subscribe(console.log);
```

I can see the subscription event being sent with the access_token, etc, and acknowledgement received. 

```
topic: "realtime:public"
```

Heartbeat events are sent/received too. But no change events (INSERT, UPDATE, DELETE) reach the client at all. Replication is enabled on all tables. Could this be related or is it likely to be a different issue?

Version:
```
@supabase/supabase-js@1.29.1
```

**Comment by GaryAustin1** [comment] 2022-01-01 20:25
Not likely related, unless you have tables with function calls in their RLS policy.
First thing I would do is to verify a non-RLS table works or not to rule out RLS issues.

Second I would make sure user is logged in when making the subscribe.  Right now realtime only works with signed in user unless something has changed since I last looked at things.  You could verify by making an RLS table select write before the subscribe.

**Comment by jonlambert** [comment] 2022-01-01 22:55
Thanks for the continued help, @GaryAustin1!

> Not likely related, unless you have tables with function calls in their RLS policy. First thing I would do is to verify a non-RLS table works or not to rule out RLS issues.

A public table with RLS disabled works fine.

> Second I would make sure user is logged in when making the subscribe. Right now realtime only works with signed in user unless something has changed since I last looked at things.

Yep – a user_token seems to be passed in the payload of the phx_join message.

> Also make sure besides flipping the replication switches the tables are selected from the far right control in the UI.

I've selected "All Tables" on the far right control in the Replications section. Still no luck unfortunately 😕

**Comment by GaryAustin1** [comment] 2022-01-01 23:09
@jonlambert at least you are down to it being an RLS issue if it worked on non RLS table.  RT uses select RLS so the user will need policy set for that.  For sure simple RLS works with things like auth.uid().  For sure functions in RLS must specify the schema.table format to work until this bug gets resolved.  

IN READING THE BUG AND FIX AGAIN IT DOES look it could affect you if you select RLS policiesa referencing functions/tables etc. and then they would need schema. in front of them (like auth.uid() which I happen to have already had versus just uid())
The fix is underway, but I believe it has to be applied to Supabase servers.

**Comment by jonlambert** [comment] 2022-01-01 23:20
> at least you are down to it being an RLS issue if it worked on non RLS table.

@GaryAustin1 Yeah definitely. Good call to test on a non-RLS table.

My policies are all pretty simple: `(uid() = user_id)` - and fully qualifying the table selector (`public.test_table`) doesn't seem to help. This could be a different problem to the one this fix addresses 😕

**Comment by GaryAustin1** [comment] 2022-01-01 23:26
@jonlambert DON'T DO public.test_table in the realtime .from if that is what you mean, that will break. 
BUT DO auth.uid() or any public. on other tables in your select RLS POLICIES if you have them.

**Comment by jonlambert** [comment] 2022-01-01 23:52
@GaryAustin1 – as @tconroy [mentioned above](https://github.com/supabase/realtime/issues/213#issuecomment-1001655400), when editing the policy using the Supabase dashboard, it strips out `auth.` from the `auth.uid()` reference. I tried executing the `ALTER POLICY` SQL directly, but that doesn't change things either unfortunately. 

I don't reference any other tables in my RLS policies at the moment. They're literally as simple as `(uid() = user_id)`.

**Comment by GaryAustin1** [comment] 2022-01-02 00:02
I'm out of ideas then...
But as far as auth.uid().  The UI does show that stripped even though I added it at auth.uid() , but if I look at my actual table sql with my IDE database editor it shows:
`  with check (auth.role() = 'authenticated'::text);`
even though the UI shows:
`(role() = 'authenticated'::text)`
So I think it does actually stick if you use auth.

**Comment by jonlambert** [comment] 2022-01-02 00:04
Fair enough @GaryAustin1. Thanks for the help so far.

Ah that's interesting – I have used auth, but it doesn't seem to fix this particular problem unfortunately.

**Comment by w3b6x9** [comment] 2022-01-02 00:37
@jonlambert can you please email support@supabase.io with your project ref? i can investigate!

**Comment by GaryAustin1** [comment] 2022-01-02 01:46
@w3b6x9 @jonlambert  how ever this turns out please post a result/fix status Thanks!

**Comment by w3b6x9** [comment] 2022-01-20 01:20
we weren't able to figure out the root cause of

> When testing on a public table with RLS disabled, I get INSERT and UPDATE events, but no DELETE.

i believe i upgraded @jonlambert's project to an early preview of the latest Realtime RLS version that will be deployed this week and it fixed the project's issue. in conclusion, this issue and @jonlambert's issue are both fixed with the latest realtime (https://github.com/supabase/realtime/releases/tag/v0.20.4)

**Closed** 2022-01-31 20:58 UTC
Labels: bug

**Comment by olegkorol** [comment] 2022-08-30 19:06
Hi! Has this really been fixed? I am experiencing similar issues.

**Comment by w3b6x9** [comment] 2022-08-30 23:37
@olegkorol can you please create a [support ticket ](https://app.supabase.com/support/new)and specify which project ref(s) you're having this issue with?

**Comment by olegkorol** [comment] 2022-08-31 10:08
Thanks for the swift reply, @w3b6x9!

It seems that my problem was not related to this issue after all:
https://discord.com/channels/839993398554656828/1014224484426858627/1014470258112864319

Sorry for any inconvenience.

**Comment by LivioGama** [comment] 2023-06-09 23:54
This can also be due to this if you have trouble with realtime, upgrade supabase client to 2.24.0 https://github.com/supabase/supabase-js/commit/b55d386b35cdf9373fabbbc07199f86811bde339

**Comment by LivioGama** [comment] 2023-06-10 02:57
That was not it, I decided to write a whole medium post for avoiding you waste time in the future: https://liviogamassia.medium.com/using-supabase-rls-with-firebase-auth-custom-auth-provider-357eaad9c70f
