### ISSUE TITLE
Bug: Generated columns are missing in realtime payload

### ISSUE THREAD

**Issue by Vinzent03** [supabase/realtime#210] opened 2021-12-20 21:26 UTC
# Bug report

## Describe the bug

I'm storing coordinates with the `geography` type from postgis. To read them on the client I need to create a generated column, which transforms them with `st_astext(position)` to text.

## To Reproduce
```sql
CREATE TABLE public.test
(
    "position" geography,
    position_text text GENERATED ALWAYS AS (st_astext(position)) STORED,
    id integer NOT NULL,
    PRIMARY KEY (id)
)
```

And listen for changes in dart:
```dart
  supabaseClient.from("test").on(
      SupabaseEventTypes.all,
      (payload) {
        print("got data");// I'm checking with debugger here
      },
    ).subscribe();
```

## Expected behavior
`position` is properly decoded, which would be even better, but at least ship the generated column `position_text`.

## System information

- OS: linux
- Version of supabase-dart: 0.2.10
- I'm testing this with the cli 0.15.8

## Additional context

I checked the raw unformatted data from the socket in the realtime client, but the column wasn't there either.

**Comment by w3b6x9** [comment] 2021-12-21 00:00
@Vinzent03 just wanted to confirm that you're not receiving the `position_text` change at all using `supabase-dart`.

I just reproduced your example and in my `supabase-js` client I get the following:

```js
{
  "schema": "public",
  "table": "test",
  "commit_timestamp": "2021-12-20T23:58:15.688701+00:00",
  "eventType": "INSERT",
  "new": {
    "id": 1,
    "position": "0101000020E610000075029A081B9A5DC0F085C954C1F84040",
    "position_text": "POINT(-118.4079 33.9434)"
  },
  "old": {}
}
```

Can you post an example payload of what you're receiving on the client? This might be an issue with supabase-dart/realtime-dart.

**Comment by Vinzent03** [comment] 2021-12-21 13:53
Ok after some further testing I'm a bit confused. By using the cli (so a local db) I get the following raw data:
```json
{
    "event": "UPDATE",
    "payload": {
        "columns": [
            {
                "flags": [],
                "name": "position",
                "type": "geography",
                "type_modifier": 4294967295
            },
            {
                "flags": [
                    "key"
                ],
                "name": "id",
                "type": "int4",
                "type_modifier": 4294967295
            }
        ],
        "commit_timestamp": "2021-12-21T13:45:34Z",
        "errors": null,
        "old_record": {},
        "record": {
            "id": "2",
            "position": "0101000020E610000000000000000049400000000000804940"
        },
        "schema": "public",
        "table": "test",
        "type": "UPDATE"
    },
    "ref": null,
    "topic": "realtime:public:test"
}
```
I see now that the `old_record` field is empty. That shouldn't be the case, right?

In addition, I tested it on a new online supabase project. There I have a different problem:
```json
{
    "event": "UPDATE",
    "payload": {
        "columns": [
            {
                "name": "position",
                "type": "geography"
            },
            {
                "name": "position_text",
                "type": "text"
            },
            {
                "name": "id",
                "type": "int4"
            }
        ],
        "commit_timestamp": "2021-12-21T13:40:40.872757+00:00",
        "errors": null,
        "old_record": {
            "id": 2
        },
        "record": {
            "id": 2,
            "position": "0101000020E610000000000000000049400000000000804940",
            "position_text": "POINT(50 51)"
        },
        "schema": "public",
        "table": "test",
        "type": "UPDATE"
    },
    "ref": null,
    "topic": "realtime:public:test"
}
```
The `flags` field is missing per column, which results in an error, because it can't identify the primary key. I reported that [here](https://github.com/supabase-community/supabase-dart/issues/74), but on my testing db it isn't "fixed" as I said in my comment.

**Comment by w3b6x9** [comment] 2021-12-21 23:19
@Vinzent03 

> using the cli (so a local db) I get the following raw data

Looks like you're running the non-RLS Realtime version locally. Supabase projects are all running Realtime RLS. See docs here: https://github.com/supabase/realtime#realtime-rls

> I see now that the old_record field is empty. That shouldn't be the case, right?

If you're talking about the `INSERT` example then yes it should be empty. You can populate `old_record` on `UPDATE` changes by setting `REPLICA IDENTITY` to `FULL` on your database tables.

> I tested it on a new online supabase project. There I have a different problem

Supabase projects are running Realtime RLS which no longer output `flags` field. What is the error you're getting? All clients should be able to properly handle database changes without `flags` field.

**Comment by Vinzent03** [comment] 2021-12-22 08:39
> I see now that the old_record field is empty. That shouldn't be the case, right?

Forget that. That was from a previous example with update event. 

> Looks like you're running the non-RLS Realtime version locally. Supabase projects are all running Realtime RLS.

Shouldn't the cli use rls realtime too? Is rls realtime used, although rls is not enabled on the table?

> Supabase projects are running Realtime RLS which no longer output flags field. What is the error you're getting? All clients should be able to properly handle database changes without flags field.

Looks like my code ran with supabase-dart 0.2.9. supabase-dart 0.2.10 fixes this. Sorry, I don't know why I thought I'm on 0.2.9.

So to summarize, only the cli version doesn't include the `position_text` column and still uses non-rls realtime. Did you try it with the cli version or only with an online supabase project?

**Comment by w3b6x9** [comment] 2021-12-22 10:04
@Vinzent03 ah, that explains it! I'm running Realtime RLS locally but I just looked at `supabase/cli` and the configs point to the old non-RLS Realtime. I'll close this issue b/c it seems like it's fixed for you by version bumping `supabase-dart`. I'll create a PR over in `supabase/cli`.

**Closed by w3b6x9** 2021-12-22 10:04 UTC
Labels: bug

**Comment by w3b6x9** [comment] 2021-12-23 01:56
> @Vinzent03 ah, that explains it! I'm running Realtime RLS locally but I just looked at `supabase/cli` and the configs point to the old non-RLS Realtime. I'll close this issue b/c it seems like it's fixed for you by version bumping `supabase-dart`. I'll create a PR over in `supabase/cli`.

Here's the cli PR: https://github.com/supabase/cli/pull/115

**Comment by Vinzent03** [comment] 2021-12-23 14:54
@w3b6x9 Thanks for fixing the issue. I'm still amazed why switching to rls-realtime fixes the shipping of generated columns. It's now fixed, so I don't really care, but it wonders me.

By the way. Is adding a generated column even the best/recommended way (if there's any) to ship postgis types via realtime? Even via postgrest I needed a function to call `st_astext` or add a view.

**Comment by w3b6x9** [comment] 2021-12-23 21:47
@Vinzent03 

> I'm still amazed why switching to rls-realtime fixes the shipping of generated columns.

The previous Realtime and Realtime RLS use different plugins, `pgoutput` and `wal2json`, respectively. I suspect it has to do with `pgoutput` not handling generated columns properly.

> Is adding a generated column even the best/recommended way (if there's any) to ship postgis types via realtime?

I think it's fine now that it's working with Realtime RLS. As long as you don't mind the output format.
