### ISSUE TITLE
Phoenix tokens for channel auth

### ISSUE THREAD

**Issue by kamikazechaser** [supabase/realtime#95] opened 2020-12-28 18:31 UTC
# Feature request

## Is your feature request related to a problem? Please describe.

At the moment, channels aren't secured. Anyone with the endpoint and public key can listen to **all** db changes. This means that realtime streaming cannot be used at all on the client side. This has been mentioned as a caveat in supabase/supabase#237. However in the main docs, there is no such warning given:
* https://supabase.io/docs/client/subscribe
* https://supabase.io/docs/realtime/client/initializing

## Describe the solution you'd like

Update documentation to reflect that client-side web socket aren't authorized at the moment. Add Phoenix token verification to **all** channels.

The Phoenix token itself [seems to be a JWT](https://elixirforum.com/t/how-is-phoenix-token-different-from-jwt/2349/2) except that the payload is not in JSON. So maybe a bit of decoding/re-encoding the same token in the authorization header from JSON to "Whatever encoding Phoenix uses" might just work. Alternatively, let the burden of creating Phoenix tokens lie with the developer using the same JWT secret.

**Comment by kiwicopple** [comment] 2021-01-04 20:23
Thanks for this @kamikazechaser - we're checking if we can use our exiting JWT setup first, but if that doesn't work we'll switch to the Phoenix tokens. 

Really appreciate the ideas here 🙏

**Comment by awalias** [comment] 2021-01-11 04:17
anything else required in the rest of the stack to get this integrated?
- [ ] realtime-js to send Authorization Header?
- [ ] Worker to set SECURE_CHANNELS=true and JWT_SECRET=blah (also maybe SECRET_BASE?)
- [ ] Release new kps build with v0.10.1

**Comment by awalias** [comment] 2021-01-11 04:20
also how should we manage the breaking change with existing applications? Thinking of the scenario where we upgrade people's KPS instance

**Comment by emschwartz** [comment] 2021-01-11 04:44
If you wanted to avoid making it a sudden breaking change, you could give
the current public key the ability to subscribe to all channels, create a
new restricted public key that is limited to the row level permissions, and
deprecate or recommend against using the original public key.

>

**Comment by kiwicopple** [comment] 2021-01-11 06:14
> realtime-js to send Authorization Header?

This one is most urgent, although it is actually in `supabase-js`. 


@soedirgo is this correct? - We will need to pass the JWT [as a `param`](https://github.com/supabase/supabase-js/blob/a5dc5d252a1ec7c9c2c2a5682dd77868fe2c3a97/src/SupabaseClient.ts#L138) called "token" so that it flows through [to the channel](https://github.com/supabase/realtime-js/blob/c79862e9be9ac59d0416adad112d42d7cdcac79e/src/RealtimeClient.ts#L246) when connecting. 

If confirmed, I'll start an issue in `supabase-js`. We will need to do this soon, because it's a client-side change. Once we roll out the server-side change, our users will *have* to be on the new version, so we need to give them to upgrade their client. Luckily there isn't much they will need to do on their side besides upgrading (`npm install @supabase/supabase-js@latest).

**Comment by soedirgo** [comment] 2021-01-11 06:26
> Luckily there isn't much they will need to do on their side besides upgrading

Yeah that should be all, the new client should work fine for old projects. The only problem is using old code with new instances. This also means we need to update our examples

**Comment by w3b6x9** [comment] 2021-02-11 23:32
@kiwicopple @soedirgo @awalias I think `supabaseKey` (public-anon-key JWT) is already being passed to [SupabaseClient](https://github.com/supabase/supabase-js/blob/master/src/index.ts#L15), which in turn is passing it to [RealtimeClient](https://github.com/supabase/supabase-js/blob/33aac7438cdc12f5202cdfd13d053901382f0dd2/src/SupabaseClient.ts#L148), which is appended to Realtime endpoint url under `apikey` in [this.params](https://github.com/supabase/realtime-js/blob/master/src/RealtimeClient.ts#L296). 

We can:

1. update the key from `token` to `apikey` in Realtime socket params (see: #122)
2. worker to set `SECURE_CHANNELS=true` and `JWT_SECRET=blah`
3. release new kps build

This way, we don't have to update `supabase-js` and users don't have to do anything on their end (i.e. version bump their `supabase-js` client).

**Comment by w3b6x9** [comment] 2021-02-11 23:40
We also need to update `realtime-js` [README](https://github.com/supabase/realtime-js/blob/master/README.md), specifically replace `token` with `apikey`:

```
var client = new RealtimeClient(process.env.REALTIME_URL, { params: { token: 'token123' }})
```



That was added b/c of issue #109.

**Comment by kiwicopple** [comment] 2021-02-12 08:59
That's actually a great idea @w3b6x9 - nice. Let's do it 👍 👍 👍

**Comment by w3b6x9** [comment] 2021-02-17 21:55
Closing this issue b/c channels auth has been set and released to prod.

**Closed by w3b6x9** 2021-02-17 21:55 UTC
Labels: enhancement
